language: python
sudo: false
python: 2.7
env:
  matrix:
    - TOXENV=py27-django12
    - TOXENV=py27-django13
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18

install:
  - pip install tox
script: tox
