name: Tests

# Triggers the workflow on push or pull request events
on:
  - push
  - pull_request

jobs:
  test_with_tox:
    runs-on: ubuntu-latest

    # Define a variation to execute a job
    strategy:
      matrix:
        python-version: [3.6, 3.9]

    steps:
    # Checkout the source code
    - uses: actions/checkout@v2

    # Set up a Python environment to run tests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install the packages needed to run tox from github actions
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    # Run tox from github actions
    - name: Test with tox
      run: tox
